export { CarritoPage } from './carrito/carrito';
export { CategoriasPage } from './categorias/categorias';
export { LoginPage } from './login/login';
export { OrdenesPage } from './ordenes/ordenes';
export { OrdenesDetallePage } from './ordenes-detalle/ordenes-detalle';
export { PorCategoriaPage } from './por-categoria/por-categoria';
export { ProductoPage } from './producto/producto';
export { TabsPage } from './tabs/tabs';
export { BusquedaPage } from './busqueda/busqueda';
